### PR TITLE
Implement VRoomEditor GUI layout

### PR DESCRIPTION
**Pull request by Snowapril**
This revision implements VRoomEditor GUI initial layout

image

* Add initial GUI layout with `UI Builder`, `UI Toolkit`
* Resize camera viewport adjusted with GUI scene rectangle

### References
* https://docs.unity3d.com/Packages/com.unity.ui.builder@1.0/manual/index.html
* https://www.youtube.com/watch?v=t4tfgI1XvGs
* https://www.youtube.com/watch?v=EVXFWXaZtjw

### CODE REVIEW

**Comment by lusianm** [comment]
Good Job!

다만 Scene폴더와 Scenes폴더 중 사용 하지 않는 것은 삭제 하는 것이 좋을 것 같아.

**Comment by Snowapril** [comment]
@lusianm Good point!! I removed the unused directory `Assets/Scenes`.

**Review by lusianm — APPROVED** [review]
good job.

**Comment by Snowapril** [comment]
Thanks for review!

**Pull request merged**
